spring:
    
    application:
        name: gateway
    security:
        oauth2:
            resourceserver:
                opaquetoken:
                    introspection-uri: ${INSTROSPECTION_URI}
                    client-id: ${CLIENT_ID}
                    client-secret: ${CLIENT_SECRET}

    cloud:
        gateway:
            routes:
            - id: pacs
              uri: ${API_URI}
              predicates:
                - Path=/**

server:
        port: ${PORT:8080}